// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57zkkv1TTpTaUp_v5MfDsvs-HcbPDptI',
    appId: '1:107936409056:web:245f2674e012e5b666b785',
    messagingSenderId: '107936409056',
    projectId: 'sample-application-52283',
    authDomain: 'sample-application-52283.firebaseapp.com',
    storageBucket: 'sample-application-52283.appspot.com',
    measurementId: 'G-W31RE5FF5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BfVVXEGCDPW-ULn0V4u3LK0eBfhIpvY',
    appId: '1:107936409056:android:853c970f836901d466b785',
    messagingSenderId: '107936409056',
    projectId: 'sample-application-52283',
    storageBucket: 'sample-application-52283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpTGCUnp_d9VB8JuhDBrvM2eVZGAEj7pU',
    appId: '1:107936409056:ios:21b03c99036f9e2766b785',
    messagingSenderId: '107936409056',
    projectId: 'sample-application-52283',
    storageBucket: 'sample-application-52283.appspot.com',
    iosClientId: '107936409056-mbcutg8af5nld8s0sb71dakm9p2s54l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpTGCUnp_d9VB8JuhDBrvM2eVZGAEj7pU',
    appId: '1:107936409056:ios:21b03c99036f9e2766b785',
    messagingSenderId: '107936409056',
    projectId: 'sample-application-52283',
    storageBucket: 'sample-application-52283.appspot.com',
    iosClientId: '107936409056-mbcutg8af5nld8s0sb71dakm9p2s54l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
